version: '3'
services:
  livy:
    image: itexico-livy-server:latest
    build:
      context: .
      dockerfile: Dockerfile.livy
    hostname: livy
    ports:
      - "8998:8998"
    networks:
      - itexico-spark-notebook-network
  jupyter:
    image: itexico-jupyter-notebook:latest
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    hostname: jupyter
    ports:
      - "8888:8888"
    links:
      - livy:livy
    depends_on:
      - livy
    networks:
      - itexico-spark-notebook-network

networks:
  itexico-spark-notebook-network:
    driver: bridge
