version: '3.5'
services:
  livy:
    image: itexico-livy-server:latest
    container_name: itexico-livy-server
    build:
      context: .
      dockerfile: Dockerfile.livy
    hostname: livy
    ports:
      - "8998:8998"
    networks:
      - itexico-jupyter
  jupyter:
    image: itexico-jupyter-notebook:latest
    container_name: itexico-jupyter-notebook
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    hostname: jupyter
    ports:
      - "8888:8888"
    links:
      - livy:livy
    depends_on:
      - livy
    networks:
      - itexico-jupyter

networks:
  itexico-jupyter:
      name: itexico-jupyter
      driver: bridge
